name: Verify package
on:
  push:
    branches-ignore:
      - master

jobs:
  validate:
    name: Validate package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Install XVFB
        run: sudo apt-get install -y xvfb

      - name: Verify package
        run: xvfb-run mvn verify